import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import { NextIntlClientProvider } from "next-intl";
import theme from "../theme";
import { routing } from "../i18n/routing";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Nilo",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/Nilo/favicon.svg",
        type: "image/svg+xml",
        sizes: "any",
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = routing.defaultLocale;
  const messages = (await import(`../translate/${locale}.json`)).default;

  return (
    <html lang={locale} className={roboto.variable}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <NextIntlClientProvider
              formats={{}}
              locale={locale}
              messages={messages}
              now={new Date(0)}
              timeZone="America/Fortaleza"
            >
              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
